spring:
  application:
    name: ffmpeg-drone-inspection

  # WebFlux配置
  codec:
    max-in-memory-size: 50MB
  webflux:
    multipart:
      max-in-memory-size: 50MB
      max-disk-usage-per-part: 100MB

  # R2DBC数据库配置 - 针对MySQL 8优化
  r2dbc:
    url: r2dbc:mysql://localhost:3306/drone_detection?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1
      # MySQL 8 特定配置
      max-acquire-time: 60s
      max-create-connection-time: 30s
      # 连接验证
      validation-depth: LOCAL

  # Flyway数据库迁移配置 - 针对MySQL 8优化
  flyway:
    url: jdbc:mysql://localhost:3306/drone_detection?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true
    user: root
    password: 123456  # 注意：这里应该与r2dbc密码一致
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    # MySQL 8 特定配置
    mixed: false
    encoding: UTF-8
    sql-migration-suffixes:
      - .sql

  # Jackson JSON配置
  jackson:
    default-property-inclusion: non_null
    time-zone: Asia/Shanghai  # 修改为更明确的时区
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# 数据库相关日志配置
logging:
  level:
    root: INFO
    com.example.ffmpeg: DEBUG
    com.example.ffmpeg.service.QwenApiService: DEBUG
    com.example.ffmpeg.service.DroneImageDetectionService: DEBUG
    com.example.ffmpeg.service.DroneVideoTrackingService: DEBUG
    com.example.ffmpeg.service.DatabaseService: DEBUG
    org.springframework.web: INFO
    org.springframework.data.r2dbc: DEBUG
    io.r2dbc.mysql: DEBUG  # 专门用于MySQL R2DBC调试
    org.flywaydb: INFO  # Flyway日志
    com.zaxxer.hikari: DEBUG  # 如果使用HikariCP连接池

# 针对MySQL 8的优化配置
server:
  port: 8080
  # 针对大文件上传的超时配置
  max-http-request-size: 500MB

# 自定义数据库配置
database:
  mysql:
    # MySQL 8 连接参数
    connection-properties:
      useSSL: false
      allowPublicKeyRetrieval: true
      serverTimezone: Asia/Shanghai
      characterEncoding: utf8
      useUnicode: true
      # MySQL 8 性能优化
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      rewriteBatchedStatements: true

    # 连接池配置
    pool:
      # 适合MySQL 8的配置
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
